USE proyectodam;

INSERT INTO provincia(titulo, provincia)
VALUES
	('Álava','ALV'),
	('Castellón','CAS'),
	('León','LEO'),
	('Salamanca','SAL'),
	('Albacete','ABC'),
	('Ceuta','CEU'),
	('Lleida','LLE'),
	('Segovia','SGV'),
	('Alicante','ALA'),
	('Ciudad Real','CRE'),
	('Lugo','LUG'),
	('Sevilla','SVL'),
	('Almería','ALM'),
	('Córdoba','CBA'),
	('Madrid','MAD'),
	('Soria','SOR'),
	('Asturias','AST'),
	('A Coruña','LCO'),
	('Málaga','MAL'),
	('Tarragona','TRN'),
	('Ávila','AVL'),
	('Cuenca','CNC'),
	('Melilla','MEL'),
	('S.C. Tenerife','SCT'),
	('Badajoz','BDJ'),
	('Girona','GIR'),
	('Murcia','MUR'),
	('Teruel','TER'),
	('Baleares','BAL'),
	('Granada','GND'),
	('Navarra','NVR'),
	('Toledo','TOL'),
	('Barcelona','BCN'),
	('Guadalajara','GLJ'),
	('Ourense','OUR'),
	('Valencia','VAL'),
	('Burgos','BRG'),
	('Guipúzcoa','GPZ'),
	('Palencia','PAL'),
	('Valladolid','VLL'),
	('Cáceres','CAC'),
	('Huelva','HLV'),
	('Las Palmas','LPA'),
	('Vizcaya','VZC'),
	('Cádiz','CDZ'),
	('Huesca','HSC'),
	('Pontevedra','PNV'),
	('Zamora','ZAM'),
	('Cantabria','CTB'),
	('Jaén','JAE'),
	('La Rioja','LRJ'),
	('Zaragoza','ZAR');